//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProyectoEntities : DbContext
    {
        public ProyectoEntities()
            : base("name=ProyectoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actividades> Actividades { get; set; }
        public virtual DbSet<Asesor> Asesor { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Comuna> Comuna { get; set; }
        public virtual DbSet<Direccion> Direccion { get; set; }
        public virtual DbSet<Horario> Horario { get; set; }
        public virtual DbSet<PuntuacioAsesor> PuntuacioAsesor { get; set; }
        public virtual DbSet<PuntuacioCliente> PuntuacioCliente { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<Servicio> Servicio { get; set; }
        public virtual DbSet<Tarea> Tarea { get; set; }
        public virtual DbSet<TareaAsesor> TareaAsesor { get; set; }
    }
}
