//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Servicio()
        {
            this.Actividades = new HashSet<Actividades>();
            this.PuntuacioAsesor = new HashSet<PuntuacioAsesor>();
            this.PuntuacioCliente = new HashSet<PuntuacioCliente>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdAsesor { get; set; }
        public Nullable<int> IdDireccion { get; set; }
        public System.DateTime Fecha { get; set; }
        public int CantidadHoras { get; set; }
        public System.TimeSpan HoraInicio { get; set; }
        public System.TimeSpan HoraTermino { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Notificacion { get; set; }
        public string FormaPago { get; set; }
        public int Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actividades> Actividades { get; set; }
        public virtual Asesor Asesor { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Direccion Direccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PuntuacioAsesor> PuntuacioAsesor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PuntuacioCliente> PuntuacioCliente { get; set; }
    }
}
