//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TareaAsesor
    {
        public int Id { get; set; }
        public Nullable<int> IdAsesor { get; set; }
        public Nullable<int> IdTarea { get; set; }
    
        public virtual Asesor Asesor { get; set; }
        public virtual Tarea Tarea { get; set; }
    }
}
